# -*- coding: utf-8 -*-

from common.database import DbHelper
import time

db = DbHelper(echo_output=True, use_cache=False, owner="Test Application")
host = 'vmdevubuntu18'
name = 'xplgw'
key = 'configured'
pause = 0
print(db.get_db_name())

with db.session_scope():
    print("================= list_persons_and_accounts =======================")
    print(db.list_persons_and_accounts())
    print("================= list_all_plugin_config =======================")
    listCP = db.list_all_plugin_config()
    print(type(listCP), listCP)
    print("================= get_core_config =======================")
    core_config = db.get_core_config()
    print(type(core_config), core_config)
    print("================= list_plugin_config =======================")
    listCP = db.list_plugin_config('plugin', name, host)
    print(type(listCP), listCP)
    print("================= get_plugin_config =======================")
    listCP = db.get_plugin_config('plugin', name, host, key)
    print(type(listCP), listCP)
    print("================= set_plugin_config =======================")
    listCP = db.set_plugin_config('plugin', 'test-p', 'foohoast', 'fookey', 123456)
    print(type(listCP), listCP)
    listCP = db.set_plugin_config('plugin', 'test-p', 'foohoast', 'barkey', 'toto')
    print(type(listCP), listCP)
    time.sleep(pause)
    print("================== del_plugin_config_key ======================")
    listCP = db.del_plugin_config_key('plugin', 'test-p', 'foohoast', 'fookey')
    print(type(listCP), listCP)
    time.sleep(pause)
#    print("================== del_plugin_config ======================")
#    listCP = db.del_plugin_config('plugin', 'test-p', 'foohoast')
#    print(type(listCP), listCP)
    print("================== set_core_config ======================")
    core_config['external_port'] = str(int(core_config['external_port'])+3)
    db.set_core_config(core_config)
    print(type(core_config), core_config)
    print("================== add_plugin_history ======================")
    name ='test-p'
    host = 'foohoast'
    hValue = db.add_plugin_history('plugin', name, host, 'starting', pl_comment="Autostart", date=time.time())
    print(type(hValue), hValue)
    hValue = db.add_plugin_history('plugin', name, host, 'started', pl_comment="Autostart", date=time.time())
    print(type(hValue), hValue)
    hValue = db.add_plugin_history('plugin', name, host, 'started', pl_comment="Autostart", date=time.time())
    print(type(hValue), hValue)
    time.sleep(1)
    hValue = db.add_plugin_history('plugin', name, host, 'alive', pl_comment="", date=time.time())
    print(type(hValue), hValue)
    time.sleep(1)
    hValue = db.add_plugin_history('plugin', name, host, 'alive', pl_comment="", date=time.time())
    print(type(hValue), hValue)
    time.sleep(10)
    hValue = db.add_plugin_history('plugin', name, host, 'alive', pl_comment="", date=time.time())
    print(type(hValue), hValue)
    time.sleep(pause)
    time.sleep(10)
    hValue = db.add_plugin_history('plugin', name, host, 'stopping', pl_comment="user stop", date=time.time())
    print(type(hValue), hValue)
    time.sleep(0)
    hValue = db.add_plugin_history('plugin', name, host, 'stopped', pl_comment="", date=time.time())
    print(type(hValue), hValue)
    time.sleep(15)
    hValue = db.list_plugin_history('plugin', name, host)
    print(type(hValue), hValue)
    print("================== del_plugin_config ======================")
    listCP = db.del_plugin_config('plugin',  name, host)
    print(type(listCP), listCP)
